name: self-hosted runner test

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Who am I
        run: |
          hostname
          whoami
          pwd

      - name: Hello
        run: echo "Hello from self-hosted runner 🚀"
